// LFOwn — phase 0 mainnet canary.
//
// Same flow as the devnet spike, but the quote asset is a real MetaDAO ownership
// coin and the money is real. THIS SCRIPT SPENDS FUNDS.
//
//   node scripts/canary-mainnet.mjs                  # dry run, sends nothing
//   LFOWN_ARM=yes node scripts/canary-mainnet.mjs    # actually signs and sends
//
// Wallet: set LFOWN_KEYPAIR to a keypair json path (defaults to ~/.config/solana/id.json).
// Keep the amounts small — this exists to prove the mechanism, not to launch anything.

import { Connection, Keypair, LAMPORTS_PER_SOL, PublicKey, sendAndConfirmTransaction } from '@solana/web3.js'
import { getAccount, getAssociatedTokenAddress } from '@solana/spl-token'
import {
  DynamicBondingCurveClient, buildCurve, SwapMode,
  TokenType, TokenDecimal, ActivationType, CollectFeeMode,
  MigrationOption, MigrationFeeOption, BaseFeeMode, TokenAuthorityOption,
  DEFAULT_MIGRATED_POOL_FEE_PARAMS,
} from '@meteora-ag/dynamic-bonding-curve-sdk'
import BN from 'bn.js'
import { readFileSync, existsSync } from 'node:fs'
import { homedir } from 'node:os'
import { FEES } from '../src/lib/config.mjs'

// CRED: ~$990k liquidity, 2.3% cost to exit $25k — the safest real quote asset today.
const QUOTE_MINT = new PublicKey('CREDBHvVqREBCAxMihzr8D1nepHMr2gmQoZWpmgGmeta')
const QUOTE_SYMBOL = 'CRED'
const RAISE = 5            // quote tokens to graduate — keep it tiny
const FIRST_BUY = 1        // quote tokens spent on the opening buy

const ARMED = process.env.LFOWN_ARM === 'yes'
// The deployer key is generated by `npm run keygen` and only ever pays rent —
// fees are claimed by FEES.recipient, which this key has no authority over.
const KEYPAIR_PATH = process.env.LFOWN_KEYPAIR
  ?? (existsSync('.keys/lfown-deployer.json') ? '.keys/lfown-deployer.json' : `${homedir()}/.config/solana/id.json`)
const RPC = readFileSync('.dev.vars', 'utf8').match(/https:\/\/[^\s"]+/)[0]

const payer = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(readFileSync(KEYPAIR_PATH, 'utf8'))))
const connection = new Connection(RPC, 'confirmed')
const client = new DynamicBondingCurveClient(connection, 'confirmed')

const send = async (tx, signers = []) => {
  tx.feePayer = payer.publicKey
  if (!ARMED) return '(dry run — not sent)'
  return sendAndConfirmTransaction(connection, tx, [payer, ...signers], { commitment: 'confirmed' })
}

console.log(ARMED ? '*** ARMED — this will spend real funds ***' : 'dry run — set LFOWN_ARM=yes to send')
console.log('wallet :', payer.publicKey.toBase58())
console.log('SOL    :', (await connection.getBalance(payer.publicKey)) / LAMPORTS_PER_SOL)

const sol = await connection.getBalance(payer.publicKey)
if (sol < 20_000_000 && !process.env.LFOWN_SKIP_BALANCE) {
  console.log(`\nNeed about 0.02 SOL for rent and fees. Send some to ${payer.publicKey.toBase58()},`)
  console.log('or point at a funded wallet with LFOWN_KEYPAIR=/path/to/keypair.json')
  process.exit(1)
}

const quoteAta = await getAssociatedTokenAddress(QUOTE_MINT, payer.publicKey)
const held = await getAccount(connection, quoteAta).then(a => Number(a.amount) / 1e6).catch(() => 0)
console.log(`${QUOTE_SYMBOL}   :`, held)
if (held < RAISE + FIRST_BUY && !process.env.LFOWN_SKIP_BALANCE) {
  console.log(`\nNeed at least ${RAISE + FIRST_BUY} ${QUOTE_SYMBOL}. Buy some on Jupiter first, then re-run.`)
  console.log('(set LFOWN_SKIP_BALANCE=1 to dry-run the instruction building anyway)')
  process.exit(1)
}

const curve = buildCurve({
  token: {
    tokenType: TokenType.SPL,
    tokenBaseDecimal: TokenDecimal.SIX,
    tokenQuoteDecimal: TokenDecimal.SIX,
    tokenAuthorityOption: TokenAuthorityOption.Immutable,
    totalTokenSupply: 1_000_000_000,
    leftover: 0,
  },
  fee: {
    baseFeeParams: {
      baseFeeMode: BaseFeeMode.FeeSchedulerLinear,
      // The same fee the real configs charge — see scripts/create-config.mjs.
      feeSchedulerParam: { startingFeeBps: FEES.totalBps, endingFeeBps: FEES.totalBps, numberOfPeriod: 0, totalDuration: 0 },
    },
    dynamicFeeEnabled: true,
    collectFeeMode: CollectFeeMode.QuoteToken,
    creatorTradingFeePercentage: FEES.creatorSharePct,
    poolCreationFee: 0,
    enableFirstSwapWithMinFee: false,
  },
  migration: {
    migrationOption: MigrationOption.MET_DAMM_V2,
    migrationFeeOption: MigrationFeeOption.FixedBps100,
    migrationFee: { feePercentage: 0, creatorFeePercentage: 0 },
    migratedPoolFee: DEFAULT_MIGRATED_POOL_FEE_PARAMS,
  },
  liquidityDistribution: {
    partnerPermanentLockedLiquidityPercentage: 50,
    partnerLiquidityPercentage: 0,
    creatorPermanentLockedLiquidityPercentage: 50,
    creatorLiquidityPercentage: 0,
  },
  lockedVesting: {
    totalLockedVestingAmount: 0, numberOfVestingPeriod: 0, cliffUnlockAmount: 0,
    totalVestingDuration: 0, cliffDurationFromMigrationTime: 0,
  },
  activationType: ActivationType.Slot,
  percentageSupplyOnMigration: 20,
  migrationQuoteThreshold: RAISE,
})

console.log('\nabout to create:')
console.log(`  a DBC config quoted in ${QUOTE_SYMBOL}, graduating at ${RAISE} ${QUOTE_SYMBOL}`)
console.log(`  trading fee ${FEES.totalBps / 100}%, split ${100 - FEES.creatorSharePct}/${FEES.creatorSharePct} partner/creator`)
console.log(`  fee claimer ${FEES.recipient}, leftovers to ${FEES.treasury}`)
console.log(`  then one token launched on it, and a ${FIRST_BUY} ${QUOTE_SYMBOL} opening buy`)

const config = Keypair.generate()
const configTx = await client.partner.createConfig({
  config: config.publicKey,
  feeClaimer: new PublicKey(FEES.recipient),
  leftoverReceiver: new PublicKey(FEES.treasury), // the DAO, not the key that signs
  quoteMint: QUOTE_MINT,
  payer: payer.publicKey,
  ...curve,
})
console.log('\n[1] config :', await send(configTx, [config]), '\n    ', config.publicKey.toBase58())

if (!ARMED) {
  // createPool reads the config account from chain, so it cannot be dry-run before
  // the config exists. Getting this far means the config instruction built cleanly
  // against a real ownership coin as quote mint.
  console.log('\nDry run complete — the config instruction builds against a real ownership coin.')
  console.log('Re-run with LFOWN_ARM=yes (and enough CRED in the wallet) to send.')
  process.exit(0)
}

const baseMint = Keypair.generate()
const poolTx = await client.creator.createPool({
  baseMint: baseMint.publicKey,
  config: config.publicKey,
  name: 'LFOwn Canary',
  symbol: 'CANARY',
  uri: 'https://example.invalid/canary.json', // a rehearsal, not a launch: no metadata to publish
  payer: payer.publicKey,
  poolCreator: payer.publicKey,
})
console.log('[2] launch :', await send(poolTx, [baseMint]), '\n    ', baseMint.publicKey.toBase58())

const { publicKey: pool } = await client.state.getPoolByBaseMint(baseMint.publicKey)
const buyTx = await client.pool.swap2({
  owner: payer.publicKey, payer: payer.publicKey, pool,
  amountIn: new BN(FIRST_BUY * 1e6), minimumAmountOut: new BN(0),
  swapMode: SwapMode.PartialFill, swapBaseForQuote: false, referralTokenAccount: null,
})
console.log('[3] buy    :', await send(buyTx))

const { poolState } = await client.state.getPool(pool)
console.log('\nquote reserve:', Number(poolState.quoteReserve.toString()) / 1e6, QUOTE_SYMBOL)
console.log('progress     :', ((await client.state.getPoolQuoteTokenCurveProgress(pool)) * 100).toFixed(1) + '%')
console.log('\nCANARY LIVE — a memecoin trading against a real ownership coin.')
