// LFOwn — open an ownership coin for launches.
//
// One DBC config per ownership coin, created once, reused by every creator who
// launches against it. LFOwn is the fee claimer; the 50/50 split with the creator
// is baked into the config, not decided per launch.
//
//   node scripts/create-config.mjs <mint|all> [starter|standard|serious]   # dry run
//   LFOWN_ARM=yes node scripts/create-config.mjs all starter              # sends
//   LFOWN_ARM=yes node scripts/create-config.mjs <mint> starter --wait    # waits for a new coin to list
//   LFOWN_ARM=yes node scripts/create-config.mjs <mint> starter --price 0.014   # a price you set
//
// `--wait` is for a raise that has not closed yet: the coin has no market and no price,
// so there is nothing to convert the tier's dollar target with. It checks MetaDAO's
// market API every minute and opens the config as soon as the coin trades there — the
// same moment it appears in the launch page's catalogue, so a config is never waiting on
// a coin nobody can pick, nor the other way round.
//
// `--price <usd>` converts the tier at a price given by hand instead — the ICO price of a
// raise that has just closed, say, rather than whatever the first minutes of trading
// print. It works for a coin that is not listed yet; the config then exists before the
// coin reaches the catalogue, and nobody can launch on it until it does.
//
// Coins already open on that tier are skipped, and each new config is published to
// KV as soon as it confirms — a config nobody can look up may as well not exist.
//
// One config per coin per tier: the graduation threshold is stored in the config,
// so a creator picks a tier rather than typing a raise amount.
//
// Then publish the address so the app can find it:
//   npx wrangler kv key put --binding REGISTRY "config:<mint>" "<config address>" --remote

import { Connection, Keypair, PublicKey, sendAndConfirmTransaction } from '@solana/web3.js'
import {
  DynamicBondingCurveClient, buildCurve,
  TokenType, TokenDecimal, ActivationType, CollectFeeMode,
  MigrationOption, MigrationFeeOption, BaseFeeMode, TokenAuthorityOption,
  DEFAULT_MIGRATED_POOL_FEE_PARAMS,
} from '@meteora-ag/dynamic-bonding-curve-sdk'
import { readFileSync, existsSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { homedir } from 'node:os'
import { FEES, TIERS } from '../src/lib/config.mjs'

const argv = process.argv.slice(2)
const flag = (name) => {
  const i = argv.findIndex((a) => a === `--${name}` || a.startsWith(`--${name}=`))
  if (i < 0) return undefined
  return argv[i].includes('=') ? argv[i].split('=')[1] : argv[i + 1]
}
const PRICE = flag('price') === undefined ? null : Number(flag('price'))
if (PRICE !== null && !(PRICE > 0)) { console.error('--price must be a positive USD price, e.g. --price 0.014'); process.exit(1) }
const WAIT = argv.includes('--wait') && PRICE === null
// Positional arguments: whatever is neither a flag nor a flag's value.
const args = argv.filter((a, i) => !a.startsWith('--') && !(argv[i - 1] === '--price'))
const target = args[0]
const tierId = args[1] ?? 'starter'
const tier = TIERS.find((t) => t.id === tierId)
if (!target || !tier) {
  console.error(`usage: node scripts/create-config.mjs <mint|all> [${TIERS.map((t) => t.id).join('|')}]`)
  process.exit(1)
}

const ARMED = process.env.LFOWN_ARM === 'yes'
const RPC = readFileSync('.dev.vars', 'utf8').match(/https:\/\/[^\s"]+/)[0]
// The deployer key is generated by `npm run keygen` and only ever pays rent —
// fees are claimed by FEES.recipient, which this key has no authority over.
const KEYPAIR_PATH = process.env.LFOWN_KEYPAIR
  ?? (existsSync('.keys/lfown-deployer.json') ? '.keys/lfown-deployer.json' : `${homedir()}/.config/solana/id.json`)
const payer = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(readFileSync(KEYPAIR_PATH, 'utf8'))))

const connection = new Connection(RPC, 'confirmed')
const client = new DynamicBondingCurveClient(connection, 'confirmed')

const { buildRegistry } = await import('../src/lib/registry.mjs')
let { coins } = await buildRegistry()

// A tier is a dollar target, converted once at today's price. From then on the
// threshold is a fixed number of backing coins and its dollar value floats.
let queue = target === 'all' ? coins : coins.filter((c) => c.mint === target)
if (PRICE !== null) {
  if (target === 'all') { console.error('--price applies to one coin: pass its mint, not all'); process.exit(1) }
  let listed = queue[0]
  if (!listed) {
    // Not in the catalogue yet: its name comes from its own on-chain metadata.
    const asset = await fetch(RPC, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'getAsset', params: { id: target } }),
    }).then((r) => r.json()).catch(() => null)
    const meta = asset?.result?.content?.metadata
    if (!meta) { console.error('no token found at', target); process.exit(1) }
    listed = { mint: target, symbol: meta.symbol || target.slice(0, 4), name: meta.name }
    console.log(`${listed.symbol} (${listed.name}) is not listed yet; opening it at the price given.`)
  }
  queue = [{ ...listed, usdPrice: PRICE }]
}
if (!queue.length && WAIT && target !== 'all') {
  console.log(`${target} is not listed on MetaDAO's market API yet. Checking every minute; Ctrl-C to stop.`)
  while (!queue.length) {
    await new Promise((r) => setTimeout(r, 60_000))
    ;({ coins } = await buildRegistry().catch((e) => { console.log(`  (market API: ${e.message})`); return { coins: [] } }))
    queue = coins.filter((c) => c.mint === target)
    if (!queue.length) console.log(`  ${new Date().toISOString().slice(11, 19)} not yet`)
  }
  console.log(`listed: ${queue[0].symbol} at $${queue[0].usdPrice}, treasury $${Math.round(queue[0].treasury).toLocaleString('en-US')}\n`)
}
if (!queue.length) { console.error('not a listed ownership coin:', target, WAIT ? '' : '(add --wait if its raise has not closed yet)'); process.exit(1) }

console.log(ARMED ? '*** ARMED ***' : 'dry run — set LFOWN_ARM=yes to send')
console.log('tier       :', `${tier.label} — $${tier.usd.toLocaleString('en-US')} per coin`)
console.log('payer      :', payer.publicKey.toBase58(), `(${KEYPAIR_PATH})`)
console.log('fee claimer:', FEES.recipient)
if (FEES.treasury !== FEES.recipient) console.log('fees land on:', FEES.treasury)
console.log('trading fee:', `${FEES.totalBps / 100}% — ${FEES.creatorSharePct}% creator / ${100 - FEES.creatorSharePct}% DAO`)

// A config is one 1048-byte account: rent-exempt reserve plus the signature fee.
// Checking here turns an unreadable "no record of a prior credit" simulation
// failure into a number and an address.
const CONFIG_ACCOUNT_BYTES = 1048
const rent = await connection.getMinimumBalanceForRentExemption(CONFIG_ACCOUNT_BYTES)
const each = rent + 10_000

/** Already open? KV is the record, so ask it rather than guessing. */
function openedAlready(mint) {
  try {
    const out = execFileSync('npx', ['wrangler', 'kv', 'key', 'get', '--binding', 'REGISTRY', `config:${mint}:${tier.id}`, '--remote'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] })
    return out.trim().startsWith('{')
  } catch { return false }
}

const todo = []
for (const coin of queue) {
  if (openedAlready(coin.mint)) {
    console.log(`  skip ${coin.symbol.padEnd(9)} already open on ${tier.id}`)
    continue
  }
  todo.push({ ...coin, threshold: Math.round(tier.usd / coin.usdPrice) })
}

if (!todo.length) { console.log('\nnothing to do.'); process.exit(0) }

const balance = await connection.getBalance(payer.publicKey)
console.log(`\nto open      : ${todo.length} coin(s)`)
console.log('cost         :', `${((each * todo.length) / 1e9).toFixed(5)} SOL`)
console.log('balance      :', `${(balance / 1e9).toFixed(5)} SOL`)

if (balance < each * todo.length) {
  console.error(`\nNot enough SOL. Send at least ${((each * todo.length - balance) / 1e9).toFixed(4)} SOL to:`)
  console.error(`  ${payer.publicKey.toBase58()}`)
  process.exit(1)
}

for (const coin of todo) {
  console.log(`\n${coin.symbol} — ${coin.threshold.toLocaleString('en-US')} ${coin.symbol} ($${tier.usd.toLocaleString('en-US')} at $${coin.usdPrice.toFixed(4)})`)

  const curve = buildCurve({
    token: {
      tokenType: TokenType.SPL,
      tokenBaseDecimal: TokenDecimal.SIX,
      tokenQuoteDecimal: TokenDecimal.SIX, // every ownership coin is 6
      tokenAuthorityOption: TokenAuthorityOption.Immutable,
      totalTokenSupply: 1_000_000_000,
      leftover: 0,
    },
    fee: {
      baseFeeParams: {
        baseFeeMode: BaseFeeMode.FeeSchedulerLinear,
        feeSchedulerParam: {
          startingFeeBps: FEES.totalBps, endingFeeBps: FEES.totalBps,
          numberOfPeriod: 0, totalDuration: 0,
        },
      },
      dynamicFeeEnabled: true,
      collectFeeMode: CollectFeeMode.QuoteToken,
      creatorTradingFeePercentage: FEES.creatorSharePct,
      poolCreationFee: 0,
      enableFirstSwapWithMinFee: false,
    },
    migration: {
      migrationOption: MigrationOption.MET_DAMM_V2,
      migrationFeeOption: MigrationFeeOption.FixedBps100,
      migrationFee: { feePercentage: 0, creatorFeePercentage: 0 },
      migratedPoolFee: DEFAULT_MIGRATED_POOL_FEE_PARAMS,
    },
    liquidityDistribution: {
      partnerPermanentLockedLiquidityPercentage: 50,
      partnerLiquidityPercentage: 0,
      creatorPermanentLockedLiquidityPercentage: 50,
      creatorLiquidityPercentage: 0,
    },
    lockedVesting: {
      totalLockedVestingAmount: 0, numberOfVestingPeriod: 0, cliffUnlockAmount: 0,
      totalVestingDuration: 0, cliffDurationFromMigrationTime: 0,
    },
    activationType: ActivationType.Slot,
    percentageSupplyOnMigration: 20,
    migrationQuoteThreshold: coin.threshold,
  })

  const config = Keypair.generate()
  if (!ARMED) { console.log('  would create', config.publicKey.toBase58()); continue }

  const tx = await client.partner.createConfig({
    config: config.publicKey,
    feeClaimer: new PublicKey(FEES.recipient),
    leftoverReceiver: new PublicKey(FEES.treasury),
    quoteMint: new PublicKey(coin.mint),
    payer: payer.publicKey,
    ...curve,
  })
  tx.feePayer = payer.publicKey

  try {
    const sig = await sendAndConfirmTransaction(connection, tx, [payer, config], { commitment: 'confirmed' })
    console.log('  tx    ', sig)
    console.log('  config', config.publicKey.toBase58())

    // Publish straight away: a config nobody can find is a config that does not exist.
    // The fee is recorded here so the launch screen can quote what this config
    // really charges rather than what the code currently intends to charge.
    const value = JSON.stringify({
      config: config.publicKey.toBase58(),
      threshold: coin.threshold,
      feeBps: FEES.totalBps,
      creatorSharePct: FEES.creatorSharePct,
      feeClaimer: FEES.recipient,
      treasury: FEES.treasury,
      openedAt: new Date().toISOString(),
    })
    execFileSync('npx', ['wrangler', 'kv', 'key', 'put', '--binding', 'REGISTRY', `config:${coin.mint}:${tier.id}`, value, '--remote'], { stdio: ['ignore', 'ignore', 'inherit'] })
    console.log('  published to KV')
  } catch (e) {
    console.error('  failed:', e.message.split('\n')[0])
  }
}

console.log('\ndone.')
